version: "3"

services:
  money_mori_member_postgres14:
    image: postgres:14
    container_name: money_mori_member_postgres14_rdb
    environment:
      TZ: Asia/Seoul
      POSTGRES_DB: "${MEMBER_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - "5432:5432"
    volumes:
      - member_sticky_volume:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d:ro
    env_file:
      - .env
    restart: always

  money_mori_redis:
    image: redis:7.0
    container_name: money_mori_redis7
    ports:
      - "6379:6379"
    volumes:
      - sticky_volume_redis:/redis/data
      - ./config/redis.conf:/usr/local/conf/redis.conf
    # 컨테이너에 docker label을 이용해서 메타데이터 추가
    labels:
      - "name=redis"
      - "mode=standalone"
    # 컨테이너 종료시 재시작 여부 설정
    restart: always
    command: redis-server /usr/local/conf/redis.conf

volumes:
  member_sticky_volume:
  sticky_volume_redis: